# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.CharField(max_length=500, verbose_name='Resumo')),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pesquisador', verbose_name='Pesquisador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['titulo'],
            },
        ),
    ]
