# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('modalidade', models.CharField(choices=[('artigo', 'Artigo Científico'), ('livro', 'Livro Impresso'), ('ebook', 'E-book')], max_length=100, verbose_name='Modalidade')),
                ('area', models.CharField(max_length=200, verbose_name='Area do Conhecimento')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pesquisador', verbose_name='Pesquisador')),
            ],
            options={
                'verbose_name': 'Publicação',
                'ordering': ['titulo'],
                'verbose_name_plural': 'Publicações',
            },
        ),
    ]
