# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('participacao', 'Participação de Eventos'), ('organizacao', 'Organização de Eventos')], max_length=100, verbose_name='Tipo de Aplicação')),
                ('area', models.CharField(max_length=200, verbose_name='Area do Conhecimento')),
                ('pais', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('estado', models.CharField(choices=[('RIO BRANCO - AC', 'Acre'), ('MACEIO - AL', 'Alagoas'), ('MACAPA -AP', 'Amapá'), ('MANAUS - AM', 'Amazonas'), ('SALVADOR - BA', 'Bahia'), ('FORTALEZA - CE', 'Ceará'), ('BRASILIA - DF', 'Distrito Federal'), ('VITORIA - ES', 'Espírito Santo'), ('GOIANIA - GO', 'Goiás'), ('SAO LUIS - MA', 'Maranhão'), ('BELO HORIZONTE - MG', 'Minas Gerais'), ('CAMPO GRANDE - MS', 'Mato Grosso do Sul'), ('CUIABA - MT', 'Mato Grosso'), ('BELEM - PA', 'Pará'), ('JOAO PESSOA - PB', 'Paraíba'), ('RECIFE - PE', 'Pernambuco'), ('TERESINA, PI', 'Piauí'), ('CURITIBA - PR', 'Paraná'), ('RIO DE JANEIRO - RJ', 'Rio de Janeiro'), ('NATAL - RN', 'Rio Grande do Norte'), ('PORTO VELHO - RO', 'Rondônia'), ('BOA VISTA - RR', 'Roraima'), ('PORTO ALEGRE - RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS - SC', 'Santa Catarina'), ('ARACAJU - SE', 'Sergipe'), ('SAO PAULO - SP', 'São Paulo'), ('PALMAS - TO', 'Tocantins')], max_length=50, verbose_name='Estado')),
                ('data', models.DateField(verbose_name='Vigência')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pesquisador', verbose_name='Pesquisador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
