# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(choices=[('RIO BRANCO - AC', 'Acre'), ('MACEIO - AL', 'Alagoas'), ('MACAPA -AP', 'Amapá'), ('MANAUS - AM', 'Amazonas'), ('SALVADOR - BA', 'Bahia'), ('FORTALEZA - CE', 'Ceará'), ('BRASILIA - DF', 'Distrito Federal'), ('VITORIA - ES', 'Espírito Santo'), ('GOIANIA - GO', 'Goiás'), ('SAO LUIS - MA', 'Maranhão'), ('BELO HORIZONTE - MG', 'Minas Gerais'), ('CAMPO GRANDE - MS', 'Mato Grosso do Sul'), ('CUIABA - MT', 'Mato Grosso'), ('BELEM - PA', 'Pará'), ('JOAO PESSOA - PB', 'Paraíba'), ('RECIFE - PE', 'Pernambuco'), ('TERESINA, PI', 'Piauí'), ('CURITIBA - PR', 'Paraná'), ('RIO DE JANEIRO - RJ', 'Rio de Janeiro'), ('NATAL - RN', 'Rio Grande do Norte'), ('PORTO VELHO - RO', 'Rondônia'), ('BOA VISTA - RR', 'Roraima'), ('PORTO ALEGRE - RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS - SC', 'Santa Catarina'), ('ARACAJU - SE', 'Sergipe'), ('SAO PAULO - SP', 'São Paulo'), ('PALMAS - TO', 'Tocantins')], default=1, max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='pais',
            field=models.CharField(default=0.0004957858205255329, max_length=50, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='estado',
            field=models.CharField(choices=[('RIO BRANCO - AC', 'Acre'), ('MACEIO - AL', 'Alagoas'), ('MACAPA -AP', 'Amapá'), ('MANAUS - AM', 'Amazonas'), ('SALVADOR - BA', 'Bahia'), ('FORTALEZA - CE', 'Ceará'), ('BRASILIA - DF', 'Distrito Federal'), ('VITORIA - ES', 'Espírito Santo'), ('GOIANIA - GO', 'Goiás'), ('SAO LUIS - MA', 'Maranhão'), ('BELO HORIZONTE - MG', 'Minas Gerais'), ('CAMPO GRANDE - MS', 'Mato Grosso do Sul'), ('CUIABA - MT', 'Mato Grosso'), ('BELEM - PA', 'Pará'), ('JOAO PESSOA - PB', 'Paraíba'), ('RECIFE - PE', 'Pernambuco'), ('TERESINA, PI', 'Piauí'), ('CURITIBA - PR', 'Paraná'), ('RIO DE JANEIRO - RJ', 'Rio de Janeiro'), ('NATAL - RN', 'Rio Grande do Norte'), ('PORTO VELHO - RO', 'Rondônia'), ('BOA VISTA - RR', 'Roraima'), ('PORTO ALEGRE - RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS - SC', 'Santa Catarina'), ('ARACAJU - SE', 'Sergipe'), ('SAO PAULO - SP', 'São Paulo'), ('PALMAS - TO', 'Tocantins')], default='nulo', max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='instituicao',
            field=models.ForeignKey(default='nulo', on_delete=django.db.models.deletion.CASCADE, to='app.Instituicao', verbose_name='Instituição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='pais',
            field=models.CharField(default='nulo', max_length=50, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País'),
        ),
    ]
