# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180227_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='pais',
        ),
    ]
