# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180227_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('bolsa', 'Bolsa'), ('participacao', 'Participação em Eventos'), ('organizacao', 'Organização de Eventos'), ('projeto', 'Projeto'), ('publicacao', 'Publicação')], max_length=100, verbose_name='Tipo de Aplicação')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('ano', models.CharField(choices=[('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '1014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011')], max_length=200, verbose_name='Ano')),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('recurso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Global do Edital')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Faixa',
                'verbose_name_plural': 'Faixas',
            },
        ),
        migrations.AddField(
            model_name='publicacao',
            name='instituicao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Instituicao', verbose_name='Instituição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='estado',
            field=models.CharField(choices=[('RIOBRANCO-AC', 'Acre'), ('MACEIO-AL', 'Alagoas'), ('MACAPA-AP', 'Amapá'), ('MANAUS-AM', 'Amazonas'), ('SALVADOR-BA', 'Bahia'), ('FORTALEZA-CE', 'Ceará'), ('BRASILIA-DF', 'Distrito Federal'), ('VITORIA-ES', 'Espírito Santo'), ('GOIANIA-GO', 'Goiás'), ('SAOLUIS-MA', 'Maranhão'), ('BELOHORIZONTE-MG', 'Minas Gerais'), ('CAMPOGRANDE-MS', 'Mato Grosso do Sul'), ('CUIABA-MT', 'Mato Grosso'), ('BELEM-PA', 'Pará'), ('JOAOPESSOA-PB', 'Paraíba'), ('RECIFE-PE', 'Pernambuco'), ('TERESINA-PI', 'Piauí'), ('CURITIBA-PR', 'Paraná'), ('RIODEJANEIRO-RJ', 'Rio de Janeiro'), ('NATAL-RN', 'Rio Grande do Norte'), ('PORTOVELHO-RO', 'Rondônia'), ('BOAVISTA-RR', 'Roraima'), ('PORTOALEGRE-RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS-SC', 'Santa Catarina'), ('ARACAJU-SE', 'Sergipe'), ('SAOPAULO-SP', 'São Paulo'), ('PALMAS-TO', 'Tocantins')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('RIOBRANCO-AC', 'Acre'), ('MACEIO-AL', 'Alagoas'), ('MACAPA-AP', 'Amapá'), ('MANAUS-AM', 'Amazonas'), ('SALVADOR-BA', 'Bahia'), ('FORTALEZA-CE', 'Ceará'), ('BRASILIA-DF', 'Distrito Federal'), ('VITORIA-ES', 'Espírito Santo'), ('GOIANIA-GO', 'Goiás'), ('SAOLUIS-MA', 'Maranhão'), ('BELOHORIZONTE-MG', 'Minas Gerais'), ('CAMPOGRANDE-MS', 'Mato Grosso do Sul'), ('CUIABA-MT', 'Mato Grosso'), ('BELEM-PA', 'Pará'), ('JOAOPESSOA-PB', 'Paraíba'), ('RECIFE-PE', 'Pernambuco'), ('TERESINA-PI', 'Piauí'), ('CURITIBA-PR', 'Paraná'), ('RIODEJANEIRO-RJ', 'Rio de Janeiro'), ('NATAL-RN', 'Rio Grande do Norte'), ('PORTOVELHO-RO', 'Rondônia'), ('BOAVISTA-RR', 'Roraima'), ('PORTOALEGRE-RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS-SC', 'Santa Catarina'), ('ARACAJU-SE', 'Sergipe'), ('SAOPAULO-SP', 'São Paulo'), ('PALMAS-TO', 'Tocantins')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(choices=[('RIOBRANCO-AC', 'Acre'), ('MACEIO-AL', 'Alagoas'), ('MACAPA-AP', 'Amapá'), ('MANAUS-AM', 'Amazonas'), ('SALVADOR-BA', 'Bahia'), ('FORTALEZA-CE', 'Ceará'), ('BRASILIA-DF', 'Distrito Federal'), ('VITORIA-ES', 'Espírito Santo'), ('GOIANIA-GO', 'Goiás'), ('SAOLUIS-MA', 'Maranhão'), ('BELOHORIZONTE-MG', 'Minas Gerais'), ('CAMPOGRANDE-MS', 'Mato Grosso do Sul'), ('CUIABA-MT', 'Mato Grosso'), ('BELEM-PA', 'Pará'), ('JOAOPESSOA-PB', 'Paraíba'), ('RECIFE-PE', 'Pernambuco'), ('TERESINA-PI', 'Piauí'), ('CURITIBA-PR', 'Paraná'), ('RIODEJANEIRO-RJ', 'Rio de Janeiro'), ('NATAL-RN', 'Rio Grande do Norte'), ('PORTOVELHO-RO', 'Rondônia'), ('BOAVISTA-RR', 'Roraima'), ('PORTOALEGRE-RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS-SC', 'Santa Catarina'), ('ARACAJU-SE', 'Sergipe'), ('SAOPAULO-SP', 'São Paulo'), ('PALMAS-TO', 'Tocantins')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='estado',
            field=models.CharField(choices=[('RIOBRANCO-AC', 'Acre'), ('MACEIO-AL', 'Alagoas'), ('MACAPA-AP', 'Amapá'), ('MANAUS-AM', 'Amazonas'), ('SALVADOR-BA', 'Bahia'), ('FORTALEZA-CE', 'Ceará'), ('BRASILIA-DF', 'Distrito Federal'), ('VITORIA-ES', 'Espírito Santo'), ('GOIANIA-GO', 'Goiás'), ('SAOLUIS-MA', 'Maranhão'), ('BELOHORIZONTE-MG', 'Minas Gerais'), ('CAMPOGRANDE-MS', 'Mato Grosso do Sul'), ('CUIABA-MT', 'Mato Grosso'), ('BELEM-PA', 'Pará'), ('JOAOPESSOA-PB', 'Paraíba'), ('RECIFE-PE', 'Pernambuco'), ('TERESINA-PI', 'Piauí'), ('CURITIBA-PR', 'Paraná'), ('RIODEJANEIRO-RJ', 'Rio de Janeiro'), ('NATAL-RN', 'Rio Grande do Norte'), ('PORTOVELHO-RO', 'Rondônia'), ('BOAVISTA-RR', 'Roraima'), ('PORTOALEGRE-RS', 'Rio Grande do Sul'), ('FLORIANOPOLIS-SC', 'Santa Catarina'), ('ARACAJU-SE', 'Sergipe'), ('SAOPAULO-SP', 'São Paulo'), ('PALMAS-TO', 'Tocantins')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='edital',
            name='faixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faixa', verbose_name='Faixas'),
        ),
        migrations.AddField(
            model_name='edital',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Programa', verbose_name='Programa'),
        ),
    ]
